#!/usr/bin/env bash
# Loop through each file in the current dir
for file in *; do
# check if the file is not a hidden file
	if [[ ! "$file" == .* ]]; then
		# Extract the part of the name after the first dash
		file_name=$(echo "$file" | cut -d'-' -f2-)
		# print the modifies file name
		echo "$file_name"
	fi
done

